"""create profile content tables

Revision ID: 5d796727aa56
Revises: 926eafd72d47
Create Date: 2026-09-04 10:57:28.984153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d796727aa56'
down_revision: Union[str, Sequence[str], None] = '926eafd72d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_interests_display_order_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_interests_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests'))
    )
    op.create_index(op.f('ix_interests_profile_id'), 'interests', ['profile_id'], unique=False)
    op.create_table('profile_contacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            contact_type IN (\n                'EMAIL',\n                'PHONE',\n                'WHATSAPP',\n                'OTHER'\n            )\n            ", name=op.f('ck_profile_contacts_contact_type')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_profile_contacts_display_order_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_contacts_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_contacts')),
    sa.UniqueConstraint('profile_id', 'contact_type', 'value', name='profile_contact')
    )
    op.create_index(op.f('ix_profile_contacts_profile_id'), 'profile_contacts', ['profile_id'], unique=False)
    op.create_index('uq_profile_contacts_primary_type', 'profile_contacts', ['profile_id', 'contact_type'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('profile_documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            document_type IN (\n                'CV',\n                'RESUME',\n                'CERTIFICATE',\n                'OTHER'\n            )\n            ", name=op.f('ck_profile_documents_document_type')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_profile_documents_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_documents_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_documents')),
    sa.UniqueConstraint('profile_id', 'media_asset_id', name='profile_document_asset')
    )
    op.create_index(op.f('ix_profile_documents_media_asset_id'), 'profile_documents', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_profile_documents_profile_id'), 'profile_documents', ['profile_id'], unique=False)
    op.create_index('uq_profile_documents_current_type', 'profile_documents', ['profile_id', 'document_type'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('profile_media',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('media_role', sa.String(length=30), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("\n            media_role IN (\n                'AVATAR',\n                'HERO',\n                'ABOUT',\n                'BACKGROUND',\n                'OTHER'\n            )\n            ", name=op.f('ck_profile_media_media_role')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_profile_media_display_order_non_negative')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_profile_media_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_media_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_media')),
    sa.UniqueConstraint('profile_id', 'media_asset_id', name='profile_media_asset')
    )
    op.create_index(op.f('ix_profile_media_media_asset_id'), 'profile_media', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_profile_media_profile_id'), 'profile_media', ['profile_id'], unique=False)
    op.create_table('social_links',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_social_links_display_order_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_social_links_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links')),
    sa.UniqueConstraint('profile_id', 'url', name='profile_url')
    )
    op.create_index(op.f('ix_social_links_profile_id'), 'social_links', ['profile_id'], unique=False)
    op.create_table('strengths',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_strengths_display_order_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_strengths_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strengths'))
    )
    op.create_index(op.f('ix_strengths_profile_id'), 'strengths', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strengths_profile_id'), table_name='strengths')
    op.drop_table('strengths')
    op.drop_index(op.f('ix_social_links_profile_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_profile_media_profile_id'), table_name='profile_media')
    op.drop_index(op.f('ix_profile_media_media_asset_id'), table_name='profile_media')
    op.drop_table('profile_media')
    op.drop_index('uq_profile_documents_current_type', table_name='profile_documents', postgresql_where=sa.text('is_current = true'))
    op.drop_index(op.f('ix_profile_documents_profile_id'), table_name='profile_documents')
    op.drop_index(op.f('ix_profile_documents_media_asset_id'), table_name='profile_documents')
    op.drop_table('profile_documents')
    op.drop_index('uq_profile_contacts_primary_type', table_name='profile_contacts', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_profile_contacts_profile_id'), table_name='profile_contacts')
    op.drop_table('profile_contacts')
    op.drop_index(op.f('ix_interests_profile_id'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
