"""create technology tables

Revision ID: 8a55e07842f2
Revises: 5d796727aa56
Create Date: 2026-09-04 11:11:15.906673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a55e07842f2'
down_revision: Union[str, Sequence[str], None] = '5d796727aa56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('iso_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('iso_code', name=op.f('uq_languages_iso_code')),
    sa.UniqueConstraint('name', name=op.f('uq_languages_name'))
    )
    op.create_table('proficiency_levels',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.CheckConstraint('rank > 0', name=op.f('ck_proficiency_levels_rank_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proficiency_levels')),
    sa.UniqueConstraint('code', name=op.f('uq_proficiency_levels_code')),
    sa.UniqueConstraint('rank', name=op.f('uq_proficiency_levels_rank'))
    )
    op.create_table('technology_categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_technology_categories_display_order_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_technology_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_technology_categories_slug'))
    )
    op.create_table('profile_languages',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=False),
    sa.Column('proficiency_level_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_profile_languages_display_order_non_negative')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_profile_languages_language_id_languages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['proficiency_levels.id'], name=op.f('fk_profile_languages_proficiency_level_id_proficiency_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_languages_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'language_id', name=op.f('pk_profile_languages'))
    )
    op.create_index(op.f('ix_profile_languages_proficiency_level_id'), 'profile_languages', ['proficiency_level_id'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('technology_category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('icon_media_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['icon_media_id'], ['media_assets.id'], name=op.f('fk_technologies_icon_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technology_category_id'], ['technology_categories.id'], name=op.f('fk_technologies_technology_category_id_technology_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies')),
    sa.UniqueConstraint('name', name=op.f('uq_technologies_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_technologies_slug'))
    )
    op.create_index(op.f('ix_technologies_icon_media_id'), 'technologies', ['icon_media_id'], unique=False)
    op.create_index(op.f('ix_technologies_technology_category_id'), 'technologies', ['technology_category_id'], unique=False)
    op.create_table('educations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('degree', sa.String(length=180), nullable=False),
    sa.Column('field_of_study', sa.String(length=180), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_educations_display_order_non_negative')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_educations_valid_date_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_educations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_educations_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_index(op.f('ix_educations_organization_id'), 'educations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_educations_profile_id'), 'educations', ['profile_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('employment_type', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_experiences_display_order_non_negative')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_experiences_valid_date_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_experiences_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_experiences_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    op.create_index(op.f('ix_experiences_organization_id'), 'experiences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_experiences_profile_id'), 'experiences', ['profile_id'], unique=False)
    op.create_table('profile_technologies',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('technology_id', sa.BigInteger(), nullable=False),
    sa.Column('featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_profile_technologies_display_order_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_technologies_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_profile_technologies_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'technology_id', name=op.f('pk_profile_technologies'))
    )
    op.create_table('experience_highlights',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('experience_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_experience_highlights_display_order_non_negative')),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_experience_highlights_experience_id_experiences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_highlights'))
    )
    op.create_index(op.f('ix_experience_highlights_experience_id'), 'experience_highlights', ['experience_id'], unique=False)
    op.create_table('experience_technologies',
    sa.Column('experience_id', sa.BigInteger(), nullable=False),
    sa.Column('technology_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_experience_technologies_display_order_non_negative')),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_experience_technologies_experience_id_experiences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_experience_technologies_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'technology_id', name=op.f('pk_experience_technologies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_technologies')
    op.drop_index(op.f('ix_experience_highlights_experience_id'), table_name='experience_highlights')
    op.drop_table('experience_highlights')
    op.drop_table('profile_technologies')
    op.drop_index(op.f('ix_experiences_profile_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_organization_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_educations_profile_id'), table_name='educations')
    op.drop_index(op.f('ix_educations_organization_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_technologies_technology_category_id'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_icon_media_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_profile_languages_proficiency_level_id'), table_name='profile_languages')
    op.drop_table('profile_languages')
    op.drop_table('technology_categories')
    op.drop_table('proficiency_levels')
    op.drop_table('languages')
    # ### end Alembic commands ###
