"""create project portfolio tables

Revision ID: c66c25d6ac8a
Revises: 8a55e07842f2
Create Date: 2026-09-04 11:19:48.378723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66c25d6ac8a'
down_revision: Union[str, Sequence[str], None] = '8a55e07842f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_categories_display_order_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_project_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_project_categories_slug'))
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('role_summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'DRAFT',\n                'PUBLISHED',\n                'ARCHIVED'\n            )\n            ", name=op.f('ck_projects_status')),
    sa.CheckConstraint('\n            end_date IS NULL\n            OR start_date IS NULL\n            OR end_date >= start_date\n            ', name=op.f('ck_projects_valid_date_range')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_projects_display_order_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_projects_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_profile_id'), 'projects', ['profile_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('project_category_relations',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['project_categories.id'], name=op.f('fk_project_category_relations_category_id_project_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_category_relations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'category_id', name=op.f('pk_project_category_relations'))
    )
    op.create_table('project_links',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            link_type IN (\n                'REPOSITORY',\n                'LIVE_DEMO',\n                'DOCUMENTATION',\n                'CASE_STUDY',\n                'OTHER'\n            )\n            ", name=op.f('ck_project_links_link_type')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_links_display_order_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_links_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_links')),
    sa.UniqueConstraint('project_id', 'url', name='project_url')
    )
    op.create_index(op.f('ix_project_links_project_id'), 'project_links', ['project_id'], unique=False)
    op.create_table('project_media',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('media_role', sa.String(length=30), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("\n            media_role IN (\n                'COVER',\n                'SCREENSHOT',\n                'GALLERY',\n                'DIAGRAM',\n                'LOGO',\n                'OTHER'\n            )\n            ", name=op.f('ck_project_media_media_role')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_media_display_order_non_negative')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_project_media_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_media_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_media')),
    sa.UniqueConstraint('project_id', 'media_asset_id', name='project_media_asset')
    )
    op.create_index(op.f('ix_project_media_media_asset_id'), 'project_media', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_project_media_project_id'), 'project_media', ['project_id'], unique=False)
    op.create_table('project_sections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            section_type IN (\n                'OVERVIEW',\n                'PROBLEM',\n                'RESPONSIBILITIES',\n                'SOLUTION',\n                'ARCHITECTURE',\n                'CHALLENGES',\n                'RESULTS',\n                'LEARNINGS',\n                'CUSTOM'\n            )\n            ", name=op.f('ck_project_sections_section_type')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_sections_display_order_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_sections_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_sections'))
    )
    op.create_index(op.f('ix_project_sections_project_id'), 'project_sections', ['project_id'], unique=False)
    op.create_table('project_technologies',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('technology_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_technologies_display_order_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_technologies_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_project_technologies_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'technology_id', name=op.f('pk_project_technologies'))
    )
    op.create_table('project_section_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_section_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_project_section_items_display_order_non_negative')),
    sa.ForeignKeyConstraint(['project_section_id'], ['project_sections.id'], name=op.f('fk_project_section_items_project_section_id_project_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_section_items'))
    )
    op.create_index(op.f('ix_project_section_items_project_section_id'), 'project_section_items', ['project_section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_section_items_project_section_id'), table_name='project_section_items')
    op.drop_table('project_section_items')
    op.drop_table('project_technologies')
    op.drop_index(op.f('ix_project_sections_project_id'), table_name='project_sections')
    op.drop_table('project_sections')
    op.drop_index(op.f('ix_project_media_project_id'), table_name='project_media')
    op.drop_index(op.f('ix_project_media_media_asset_id'), table_name='project_media')
    op.drop_table('project_media')
    op.drop_index(op.f('ix_project_links_project_id'), table_name='project_links')
    op.drop_table('project_links')
    op.drop_table('project_category_relations')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_profile_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('project_categories')
    # ### end Alembic commands ###
